export type MediaOperation =
  | "remux"
  | "transcode"
  | "video-extract"
  | "audio"
  | "subtitle-extract"
  | "thumbnail"
  | "gif"
  | "frames";

export interface MediaFormState {
  input: string;
  outputDirectory: string;
  operation: MediaOperation;
  container: string;
  videoCodec: string;
  audioCodec: string;
  mapAll: boolean;
  preserveMetadata: boolean;
  overwrite: boolean;
  startTime: string;
  duration: string;
  videoStreamIndex: string;
  audioStreamIndex: string;
  subtitleStreamIndex: string;
  videoBitrate: string;
  crf: string;
  frameRate: string;
  width: string;
  height: string;
  scalingAlgorithm: string;
  pixelFormat: string;
  preset: string;
  videoProfile: string;
  aspectRatio: string;
  crop: string;
  rotation: string;
  flipHorizontal: boolean;
  flipVertical: boolean;
  deinterlace: boolean;
  fastStart: boolean;
  speed: number;
  audioBitrate: string;
  sampleRate: string;
  channels: string;
  volume: string;
  loudnessNormalization: boolean;
  gifFps: number;
  gifWidth: number;
}

export const defaultMediaForm: MediaFormState = {
  input: "",
  outputDirectory: "",
  operation: "transcode",
  container: "mov",
  videoCodec: "copy",
  audioCodec: "copy",
  mapAll: true,
  preserveMetadata: true,
  overwrite: false,
  startTime: "",
  duration: "",
  videoStreamIndex: "0",
  audioStreamIndex: "0",
  subtitleStreamIndex: "0",
  videoBitrate: "",
  crf: "20",
  frameRate: "",
  width: "",
  height: "",
  scalingAlgorithm: "lanczos",
  pixelFormat: "",
  preset: "medium",
  videoProfile: "",
  aspectRatio: "",
  crop: "",
  rotation: "none",
  flipHorizontal: false,
  flipVertical: false,
  deinterlace: false,
  fastStart: true,
  speed: 1,
  audioBitrate: "192k",
  sampleRate: "",
  channels: "",
  volume: "",
  loudnessNormalization: false,
  gifFps: 12,
  gifWidth: 720
};
